### ISSUE TITLE
Load routine leaves nozzle temp on 215°C

### ISSUE THREAD

**Issue by UBEXHH** [bigtreetech/PandaTouch#10]
When loading with the help of Panda Touch, the nozzle temp stays at 215° after loading.
Loading with P1 screen drops to 0° as wanted.

Fix please

**Comment by DoTsTeR77** [comment]
+1

**Comment by looxonline** [comment]
This is not true. The panda touch uses the exact load algorithm used by the X1 and P1 series machines. They will heat up, load, reduce temperature slightly, sit there for several minutes, reduce the temperature more, sit there for several minutes and finally reduce the temperature to room temp. Compare the two operations and you will find no difference.
