### ISSUE TITLE
Cannot load(use external spool) custom fillament

### ISSUE THREAD

**Issue by zeemyself** [bigtreetech/PandaTouch#107]
Panda touch not allow to load custom filament even though it shows PETG-CF value
![IMG_0232](https://github.com/user-attachments/assets/1405ba3e-3853-4b65-a296-b796be3d9d7c)

https://github.com/user-attachments/assets/60b18bc0-0295-4608-a77d-9918322a8f79

In Bambu/Orca slicer
<img width="397" alt="Screenshot 2024-08-06 at 1 49 51 PM" src="https://github.com/user-attachments/assets/7f6e605e-90c2-4fab-85dd-bf83f4ec6826">
<img width="383" alt="Screenshot 2024-08-06 at 1 50 41 PM" src="https://github.com/user-attachments/assets/4e6de48b-1a21-42e3-8235-5b3253cc6082">

**Comment by BTTJUSTIN** [comment]
After an internal discussion,the current PandaTouch's hardware resources cannot meet the request of the custom filament ,we
decided not to implement this feature

**Comment by Duffy987** [comment]
The IMG 0233.mov dosnt work. Can help somebody please?

**Comment by zeemyself** [comment]
@Duffy987 I have same issue as you 3 months ago it doesn't recognize custom filament same as yours

**Comment by Duffy987** [comment]
@zeemyself

Thanks for the information.

**Comment by Duffy987** [comment]
@zeemyself

Thanks for the information.

**Comment by bigtreetech** [comment]
This is being worked on at the moment. Looks like we have found a way to do it and it can be released in the next fw release.

**Comment by looxonline** [comment]
1.0.7. The patch versions are just for bug fixes. 1.0.7 should also bring skip object.
