### ISSUE TITLE
Firmware version 1.05 for Panda PWR

### ISSUE THREAD

**Issue by Moormerlander** [bigtreetech/PandaTouch#113]
When will firmware version 1.05 be released? My Panda PWR is about to arrive this week but without version 1.05 it can’t be used.

**Comment by Moormerlander** [comment]
Panda PWR will arrive today and firmware version 1.05 was just released. That’s a perfect timing 😊

**Comment by PrintedVisionz3D** [comment]
Do you have a link for firmware v1.05 for panda pwr? I cannot find it anywhere.  All I see on their github is v1
