### ISSUE TITLE
Panda graphic

### ISSUE THREAD

**Issue by DoTsTeR77** [bigtreetech/PandaTouch#12]
I would like the option to change the Panda graphic to something custom or at least be able to change to the bigtreetech logo.. Its nice but is a little too cartoonish for my taste.. thank you..

**Comment by UBEXHH** [comment]
Same! Makes it look cheap. Like a toy.

**Comment by Qjeezy** [comment]
I agree with this.

**Comment by andypiper** [comment]
My device has a BTT logo by default? Running firmware 1.0.1.

**Comment by DoTsTeR77** [comment]
That's there when there is no print job.  When you start a print the panda
screen cones up..

**Comment by Aerocats** [comment]
I would like a print model preview in that space as I start the print.

**Comment by looxonline** [comment]
We will consider this but it may only be for V1.0.4 release as the next release will be focused on critical bug fixes and critical functionality additions.

**Comment by looxonline** [comment]
> I would like a print model preview in that space as I start the print.

Model preview is a challenge because the preview is embedded within the zipped 3mf which means that the 3mf needs to be downloaded locally and unzipped. We may be able to do this if there is an external USB connected but that is still a variable that we need to look into.

**Comment by DoTsTeR77** [comment]
Regarding previews.. How about a small program/app running on a PC/smartphone/mac/whatever on the local network that can take care of a few things that the bambu touch does not have the horsepower for..  for example.. send it the .3mf file.. have it spit back a .jpg preview for the bambu touch to use.. it's use could be totally optional.. just an idea to throw in the hat..

**Comment by DogWzrd** [comment]
Regarding previews.. could this be done with a mqtt call to the printer like what the Home Assistant integration does ( cover image)? 
Link to their repository:  https://github.com/greghesp/ha-bambulab

**Comment by looxonline** [comment]
> Regarding previews.. could this be done with a mqtt call to the printer like what the Home Assistant integration does ( cover image)? Link to their repository: https://github.com/greghesp/ha-bambulab

This is also something that we have considered but it is not getting it from the local MQTT, it is getting it from the cloud. We are entirely able to implement this route and it was actually on the roadmap two months ago but we have paused it because we are waiting to hear more about the bambu API.

**Comment by T0MANY** [comment]
Being able to customize the graphics of the home screen would be fantastic, being able to add a user-customized image would be a very welcome feature!

**Comment by ktdevil6** [comment]
> We will consider this but it may only be for V1.0.4 release as the next release will be focused on critical bug fixes and critical functionality additions.

I hope so I think this is an important thing to have the graphic of what is printing on the screen.

**Comment by looxonline** [comment]
V1.0.3 will have a file that contains all of the PNG graphics and you can edit them to your heart's content.

**Comment by gpambrozio** [comment]
@looxonline looking at the code for the home assistant integration, it looks like this is accomplished with a direct connection to the printer. See [here](https://github.com/greghesp/ha-bambulab/blob/main/custom_components/bambu_lab/pybambu/bambu_client.py#L68)

**Comment by gpambrozio** [comment]
I managed to reverse engineer a lot of stuff and figured out a way to update the image every time you start a print (if you have a home assistant with [this integration](https://github.com/greghesp/ha-bambulab) installed.

See [here](https://github.com/bigtreetech/PandaTouch/issues/108#issuecomment-2278962552).

I'm probably going to create a proper AppDaemon app to make it easier to install using hacs.

**Comment by bigtreetech** [comment]
> @looxonline looking at the code for the home assistant integration, it looks like this is accomplished with a direct connection to the printer. See [here](https://github.com/greghesp/ha-bambulab/blob/main/custom_components/bambu_lab/pybambu/bambu_client.py#L68)

Hey Man! Thanks for the tips. Since the last comms on this thread we have figured out method to get print images to work and the functionality will be rolled out in future firmware releases.

**Comment by dilixi** [comment]
> I would like the option to change the Panda graphic to something custom or at least be able to change to the bigtreetech logo.. Its nice but is a little too cartoonish for my taste.. thank you..

@DoTsTeR77 

Hi,
there is [online tool](https://ptimgtool.bttwiki.com/) to change the panda image, and you can use it on local by this [rep](https://github.com/bigtreetech-beta/PandaTouch_Addtion_IMG).

And please close this issue thanks.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in via [online tool](https://ptimgtool.bttwiki.com/) to change the panda image, and you can use it on local by this [rep](https://github.com/bigtreetech-beta/PandaTouch_Addtion_IMG).

**Comment by BradCOnGitHub** [comment]
The linked online tool does not exist anymore

**Comment by dilixi** [comment]
> The linked online tool does not exist anymore

Hi,
We have updated its link:
https://ptimgtool.bttwiki.com/
