### ISSUE TITLE
AMS filament change leaves nozzle temp on..

### ISSUE THREAD

**Issue by DoTsTeR77** [bigtreetech/PandaTouch#13]
AMS filament load leaves nozzle temp on..  it should go back down to zero after it is done..

**Comment by UBEXHH** [comment]
Also the external manual load

It was the same load-temp problems week after week with xtouch. Annoying!
BigTreeTech should quickly update the scripting of the buttons!

**Comment by looxonline** [comment]
This is not true. It follows the exact same cool down profile that the stock BBL load function does. It will immediately go down to a lower temperature once the filament is loaded but remain there for several minutes. After that it will drop to an even lower temperature and remain there for a while. After that it will turn off completely.
