### ISSUE TITLE
Panda Touch with P1S nozzle and bed heating control

### ISSUE THREAD

**Issue by palindsay** [bigtreetech/PandaTouch#144]
Setting nozzle and bed heating temperature does not work for PS1.   I  am on latest firmware 01.06.01.00 and latest panda touch firmware.

**Comment by bigtreetech** [comment]
Please see #121

**Comment by palindsay** [comment]
But I login with Google Account, which you don't support for cloud mode.

**Comment by bigtreetech** [comment]
<img width="684" alt="image" src="https://github.com/user-attachments/assets/b125ebcf-ae04-4562-b370-c6a647e02968">

**Comment by palindsay** [comment]
Basically I had to revert to using a plain login, not google, that's not
ideal.
-phil ***@***.***)
