### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by rashuge** [bigtreetech/PandaTouch#159]
I do not have 2FA configured for the Bambu account.  I have followed the instructions online that indicate that I have to set the password for my account, I have followed that instruction set.  I have confirmed with a private browser that I can login with the password instead of the Google account.  I have to still do an email verification, however when logging in via a private browser session.  I cannot get it to authenticate.  I have global set as my region.

Panda Touch Version: 1.0.5

**Comment by dilixi** [comment]
> I do not have 2FA configured for the Bambu account. I have followed the instructions online that indicate that I have to set the password for my account, I have followed that instruction set. I have confirmed with a private browser that I can login with the password instead of the Google account. I have to still do an email verification, however when logging in via a private browser session. I cannot get it to authenticate. I have global set as my region.
> 
> Panda Touch Version: 1.0.5

Hi,
Please use this firmware:
https://github.com/bigtreetech-beta/PandaTouch-Support/tree/main/V1.0.6

**Comment by rashuge** [comment]
That worked amazingly.  Perfect.  Thank you so much.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.6

**Comment by pithon55** [comment]
404 - page not found

**Comment by pithon55** [comment]
Update link


https://github.com/bigtreetech-beta/PandaTouch-Support/tree/main/1.0.6.3
