### ISSUE TITLE
i2c connector : temperature not updating

### ISSUE THREAD

**Issue by jlo1975** [bigtreetech/PandaTouch#175]
hello
getting the brand new fresh firmware 1.0.6 to finally use the long awaited i2c connector support.
But sadly,  the temperature is not updating (you have to reboot the device to get only 1 new reading)
for info the humidity is updating correctly.

**Comment by jlo1975** [comment]
some update.
after few reboot the temperature reading update correctly every seconds.
for info here the sensor i'm using
AS-delivery dht-20 i2c (temp and humidity sensor)

**Comment by jlo1975** [comment]
some update.
after few reboot the temperature reading update correctly every seconds.
for info here the sensor i'm using
AS-delivery dht-20 i2c (temp and humidity sensor)

**Comment by looxonline** [comment]
The port is designed to work with the new Panda Sense module that will be released shortly. We cannot guarantee operation with other modules.

**Comment by TeoMM** [comment]
@jlo1975 could you take a picture to show us how you connected it? ofc it is not recommended by the manufacturer but im curious just how you made it work and how you wired it. Thanks!

**Comment by jlo1975** [comment]
i've just done a 1 to 1 wiring with the info behind the pandatouch here -> https://bttwiki.com/img/PandaTouch/pt_back.png and the info on the sensor

**Comment by jlo1975** [comment]
i've just done a 1 to 1 wiring with the info behind the pandatouch here -> https://bttwiki.com/img/PandaTouch/pt_back.png and the info on the sensor

**Comment by jlo1975** [comment]
i was lucky to found in my hardware box mess the good little white connector on pandatouch side
