### ISSUE TITLE
panda touch file transfer problem firmware 1.0.6

### ISSUE THREAD

**Issue by paolopa65** [bigtreetech/PandaTouch#185]
Hello I received the panda touch today.
I updated the firmware as per the instructions on "https://bttwiki.com/PandaTouch.html" to firmware 1.0.6 and then as requested by the panda touch the specific .img file.
Now starting a print from the panda touch, at the moment that it must be transferred to the printer, the panda touch turns off and then turns on again, as if there was no power. I tried different power supplies but the problem persists.

https://youtube.com/shorts/PeUBWGQPL8M?feature=share

**Comment by dilixi** [comment]
> Hello I received the panda touch today. I updated the firmware as per the instructions on "https://bttwiki.com/PandaTouch.html" to firmware 1.0.6 and then as requested by the panda touch the specific .img file. Now starting a print from the panda touch, at the moment that it must be transferred to the printer, the panda touch turns off and then turns on again, as if there was no power. I tried different power supplies but the problem persists.
> 
> https://youtube.com/shorts/PeUBWGQPL8M?feature=share

Hi,
Sorry for later,
I did fixed it now.

please have a try with this link:
https://github.com/bigtreetech-beta/PandaTouch-Support/blob/main/V1.0.6/panda_touch-v1.0.6.1.bin
