### ISSUE TITLE
Panda Touch reboots twice on printer connection

### ISSUE THREAD

**Issue by maple-underscore** [bigtreetech/PandaTouch#201]
On DC mode, when I turn on the printer, the Panda Touch reboots (normal) and then proceeds to reboot two more times before working. The delay between the reboots is around ~1s. (Version 1.0.6.1, printer 1.07.00.00 p1s)
Happens every time the printer is turned on with the Panda Touch on the magnetic dock.

**Comment by dilixi** [comment]
> On DC mode, when I turn on the printer, the Panda Touch reboots (normal) and then proceeds to reboot two more times before working. The delay between the reboots is around ~1s. (Version 1.0.6.1, printer 1.07.00.00 p1s) Happens every time the printer is turned on with the Panda Touch on the magnetic dock.

Hi,
Is there any different when you switch the power mode to battery?
