### ISSUE TITLE
1.0.6 Panda PWR

### ISSUE THREAD

**Issue by Wizzard1313** [bigtreetech/PandaTouch#209]
I updated to 1.0.6.2 and my Panda PWR tab disappeared. I can get it back downgrading to 1.0.5

**Comment by dilixi** [comment]
> I updated to 1.0.6.2 and my Panda PWR tab disappeared. I can get it back downgrading to 1.0.5

Hi,
There is a option to enable/disable it in Panda Touch settings.

**Comment by Wizzard1313** [comment]
I found the setting. In my opinion it should not default to off

**Comment by dilixi** [comment]
> I found the setting. In my opinion it should not default to off

Thanks,maybe We need change some logic.

**Comment by bigtreetech** [comment]
> I found the setting. In my opinion it should not default to off

So many users complained that the tab existed when they were not using the Panda PWR. We will have to investigate better logic.
