### ISSUE TITLE
Request - Support for folders and .gcode files

### ISSUE THREAD

**Issue by AndiS977** [bigtreetech/PandaTouch#21]
Please add support for (sub)folders and .gcode files on the printers SDcard.

**Comment by CyberHugger** [comment]
Please!

**Comment by looxonline** [comment]
gcode files are not supported by the BBL machines. It must be in 3mf format. Folders is already under consideration and mentioned in another issue report. Closing as a duplicate.

**Comment by AndiS977** [comment]
gcode files **are** supported. I can export as gcode files and then transfer them via ftp to the machines SD card (P1P). Then I can select them on the stock display to print. It has the advantage to start the print faster, because the embedded gcode has not to be extracted out of the 3mf.

**Comment by looxonline** [comment]
> gcode files **are** supported. I can export as gcode files and then transfer them via ftp to the machines SD card (P1P). Then I can select them on the stock display to print. It has the advantage to start the print faster, because the embedded gcode has not to be extracted out of the 3mf.

They are not supported when initiating a print over MQTT.

**Comment by AndiS977** [comment]
Ah, ok. Thank you for your answer.
