### ISSUE TITLE
Allow master/slave printer groups

### ISSUE THREAD

**Issue by Qjeezy** [bigtreetech/PandaTouch#23]
I’d like to have more than one master printer with each their own slave printers. This way we can control more than one group of printers independently from the other groups of printers. Hope that makes sense.

**Comment by papsg** [comment]
If implemented please use modern language such as "controller/worker" or something else that isn't "master/slave". The tech industry is slowly moving away from that language.

**Comment by looxonline** [comment]
Coming in V1.0.3

**Comment by dilixi** [comment]
> I’d like to have more than one master printer with each their own slave printers. This way we can control more than one group of printers independently from the other groups of printers. Hope that makes sense.

@Qjeezy 

Hi,
Please close this issue, because it was implemented on V1.0.3. Thanks.
