### ISSUE TITLE
Request - Add "Sort by" or allow tapping column header name to sort USB files.

### ISSUE THREAD

**Issue by Vantage-DS** [bigtreetech/PandaTouch#24]
Currently, files on the USB seem to be in Date order (or "Data" order as the display shows) 🙃

Allow tapping the column name header to sort by that header, descending or ascending on sequential taps.

**Comment by looxonline** [comment]
Will be considered for V1.0.3 release.

**Comment by Vantage-DS** [comment]
Will this be implemented in 1.0.4 now? I really think it's necessary at this point.
I've got 77 files that are in no discernable order and as I refine new printer settings and re-add the gcode to the Panda USB stick, the order becomes more and more chaotic.

**Comment by philchfree** [comment]
I would prefer a folder implementation

**Comment by superceleron** [comment]
> I would prefer a folder implementation

Same here

**Comment by Vantage-DS** [comment]
So would I, but that's another feature request... Not this one.

**Comment by superceleron** [comment]
btw, is already a 1.0.3 fw out that i do not know about? since i cant find it.

**Comment by Vantage-DS** [comment]
> btw, is already a 1.0.3 fw out that i do not know about? since i cant find it.

If you go on the Facebook 'Bigtreetech Panda Touch User Group', there's a post in there you can put your GitHub ID down and they'll add you to the beta test github.

**Comment by superceleron** [comment]
> > btw, is already a 1.0.3 fw out that i do not know about? since i cant find it.
> 
> If you go on the Facebook 'Bigtreetech Panda Touch User Group', there's a post in there you can put your GitHub ID down and they'll add you to the beta test github.

Thks :)

**Comment by BTTJUSTIN** [comment]
This feature was implemented in FW version V1.0.5
