### ISSUE TITLE
no ability to perform a hard reset of the unit from web interface

### ISSUE THREAD

**Issue by baconinabun** [bigtreetech/PandaTouch#26]
My TouchScreen has stopped working on a new arrived(2 day old) Panda, i've tried reflashing the firmware to see if that Factory Resets the unit, but no joy.

would be handy if the Hard/Factory reset toggle for the unit was available in the webface.

**Comment by bolsoncerrado** [comment]
my unit has stopped working after adding a P1 printer which has a broken camera lol

**Comment by looxonline** [comment]
@baconinabun Could you provide more info about what your unit is doing?

**Comment by baconinabun** [comment]
@looxonline the touch screen stopped working but the unit was displaying what it should just no touchscreen. 

my first unit came to a terrible end, my second unit has now arrived and is working fine fine.
