### ISSUE TITLE
AMS show what's in nozzle (closed)

### ISSUE THREAD

**Issue by StungDev** [bigtreetech/PandaTouch#28]
Please make the AMS tab show witch filament is in the nozzle like in the slicer and app.
![image](https://github.com/bigtreetech/PandaTouch/assets/103583641/ceb1e9d4-915c-4cc8-aa68-587d779d8288)

**Comment by papsg** [comment]
+1

**Comment by looxonline** [comment]
We will consider this for V1.0.3

**Comment by dilixi** [comment]
@StungDev 

Hi,
This was implemented on V1.0.6,Please close this issue,thanks.

![image](https://github.com/user-attachments/assets/442bb4e5-a8d1-4828-905b-52cfa9c08d22)
