### ISSUE TITLE
Use of i2c connector

### ISSUE THREAD

**Issue by andypiper** [bigtreetech/PandaTouch#29]
It looks like the i2c connector is a Grove socket - when will this be enabled?

**Comment by jlo1975** [comment]
I've received the panda touch screen and all is fine.
I'm trying to use a DHT20 humidity and temperature sensor with digital I2C output as there is a port on the back and we can see a graphical placement in the home screen.
But it seems the panda touch devise does not see it. I've tested the wiring and all is ok (tested 3.3v ).

What am I missing ? Is the external sensor with digital I2C is supported or is it planned in the futur?

**Comment by looxonline** [comment]
Coming in a future release. Closing for now.

**Comment by looxonline** [comment]
Reopening since we are starting to plan for this in V1.0.4

**Comment by looxonline** [comment]
V1.0.4 shifted focus to cloud mode because of the changes that Bambu implemented. V1.0.5 will be focused on the Panda PWR and thumbnail support. V1.0.6 will add I2C sensor support.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.6
