### ISSUE TITLE
AMS Humidity Indicator 

### ISSUE THREAD

**Issue by Aerocats** [bigtreetech/PandaTouch#30]
Please include the humidity indicator that is located in the bottom right hand corner of the AMS screen in the Handy App.

**Comment by papsg** [comment]
+1

**Comment by looxonline** [comment]
Will be considered for V1.0.3 release.

**Comment by heelsmj** [comment]
+1!

**Comment by dilixi** [comment]
> Please include the humidity indicator that is located in the bottom right hand corner of the AMS screen in the Handy App.

![image](https://github.com/user-attachments/assets/ff7f1d47-28fe-456b-87af-626b34082359)

@Aerocats 
Hi,
This was implemented on V1.0.6,Please close this issue,thanks.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.6
