### ISSUE TITLE
Settings language error "Always on"

### ISSUE THREAD

**Issue by UBEXHH** [bigtreetech/PandaTouch#37]
The setting "Always on" is spelled "Alaways on" 

...

**Comment by looxonline** [comment]
Will be fixed in the new firmware

**Comment by ModeratorPS** [comment]
Is this fixed?

**Comment by dilixi** [comment]
@UBEXHH 

Hi,
This bug was fixed on V1.0.3,please close this issue ,thanks.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.3
