### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by suxmcgee** [bigtreetech/PandaTouch#39]
I saw a request for source code was recently closed as its release is 'not planned'.

ESP32-S3 is the main MCU which means ESP-IDF tools and APIs are likely in use, as well as other compatible third-party libraries which may fall under other licensing structures.

Any open source code should be released and requests for it should not be dismissed.

**Comment by looxonline** [comment]
ESP-IDF is licensed under MIT. No other GPL libraries were used. In fact, the FTP stack was written from the ground up.
