### ISSUE TITLE
[FR] Battery stats

### ISSUE THREAD

**Issue by qwasy** [bigtreetech/PandaTouch#4]
Feature reqeust for some battery stats, like on a smartphone: battery percentage, if it is charging etc.

**Comment by G4Cab** [comment]
> Feature reqeust for some battery stats, like on a smartphone: battery percentage, if it is charging etc.

+1

**Comment by gerdj** [comment]
+1

**Comment by DoTsTeR77** [comment]
+1

**Comment by suxmcgee** [comment]
+2

**Comment by looxonline** [comment]
Duplicate but also unfortunately not supported with the current hardware.
