### ISSUE TITLE
How do I know it's getting power?

### ISSUE THREAD

**Issue by DogWzrd** [bigtreetech/PandaTouch#42]
Hi there,

I can't see when plugged in if the Panda touch is being charged or not. Is there somewhere I can see this? Or does it only charge when switched off?

thanks

**Comment by looxonline** [comment]
It charges whenever it is on the dock irrespective of the state of the switch. More info in the official wiki https://bttwiki.com/PandaTouch.html

The hardware currently does not support detecting the battery voltage and charging state but we may do a large capacity, mobile dock for it in the future that would support this.
