### ISSUE TITLE
Implementation of the Italian language

### ISSUE THREAD

**Issue by T0MANY** [bigtreetech/PandaTouch#45]
The implementation of the Italian language would be appreciated.

**Comment by looxonline** [comment]
Say it's delicious and I'll agree.

![image](https://github.com/bigtreetech/PandaTouch/assets/19784349/bec978d5-9657-402b-9f08-21cf3371d683)

**Comment by looxonline** [comment]
V1.0.4 will likely contain a JSON file with all text strings that can be edited for any language.

**Comment by looxonline** [comment]
Closing as a duplicate of #9

**Comment by dilixi** [comment]
> The implementation of the Italian language would be appreciated.

@T0MANY 

Hi,
Do you have time to do a translate for Italian?
[en-GB.zip](https://github.com/user-attachments/files/17641078/en-GB.zip)
