### ISSUE TITLE
PCB schematics for docking/loading board or type of pogo pin connectors

### ISSUE THREAD

**Issue by nurtext** [bigtreetech/PandaTouch#47]
I want to build a second docking station and wanted to ask if the schematics could be made public, so that anyone could order a second pcb e.g. from pcbway.com. If the schematics can't be made public, please release information as well as dimensions about the exact type of pogo pin connectors that have been used. Thanks.

**Comment by nurtext** [comment]
Great news, thanks!

**Comment by sanctas** [comment]
FYI: this is available on Biqu's store now.

**Comment by philchfree** [comment]
And it is available on this very repo under 3D folder
