### ISSUE TITLE
[FR] Display brightness control

### ISSUE THREAD

**Issue by qwasy** [bigtreetech/PandaTouch#5]
Feature request to change the brightness of the screen. 
Maybe with an optional "smart-auto" mode, depending on the time of the day. If it's day time the screen is brighter, when it's night the screen is darker.

**Comment by gerdj** [comment]
+1

**Comment by Vantage-DS** [comment]
Manual slider would be nice, but auto mode is probably too much to ask.

In the UK it can be dark at 4pm in winter and still light at 10pm in summer. Plus, with no built in light sensor it would never be able to account for the lights in the room being turned on or off, regardless of time of day.

**Comment by suxmcgee** [comment]
+2

**Comment by looxonline** [comment]
Coming in V1.0.3 but will be manual slider as there is no LDR and implementation of a time based auto mode is a bit much for the next release given how much will be packed into it.

**Comment by Vantage-DS** [comment]
Brightness controls seem to be working fine in beta... It's found under the Settings tab.
10-100% slider bar.
Brightness level is maintained after a power off and after going to sleep.
