### ISSUE TITLE
Printer's name on main screen

### ISSUE THREAD

**Issue by philchfree** [bigtreetech/PandaTouch#68]
FW1.03. printer's name in main screen top banner displays as: "P-<printer's name>" rather than just "printer's name"

**Comment by jlo1975** [comment]
yes a little bit ugly

**Comment by DoTsTeR77** [comment]
Yes agree.. it is ugly the wsy it is displayed

**Comment by ModeratorPS** [comment]
Same. It's not looking good :/

**Comment by looxonline** [comment]
This is required to differentiate between groups and printers.
