### ISSUE TITLE
Battery Only

### ISSUE THREAD

**Issue by mlarsen6771** [bigtreetech/PandaTouch#72]
Can't get it to stay on using the 5v selection.  Will only operate in battery mode.

**Comment by TMillesich** [comment]
This might be in conjunction with the defective UCB-C board problem:

https://www.youtube.com/channel/UCoRY1lWAIKxqTiemuJHuTzQ/community?lb=Ugkx3uZ9XZ-Ig0K5HmbVi4Z92WyStnSNCPE2

**Comment by bigtreetech** [comment]
Please request a new USB-C board via your reseller or directly from BIQU support if your purchased from us. https://biqu.equipment/pages/technical-support
