### ISSUE TITLE
Image converter for Linux / macOS

### ISSUE THREAD

**Issue by andypiper** [bigtreetech/PandaTouch#75]
Can we get the image conversion tool for Linux and macOS - would it be possible to release the source code so that we can compile it ourselves?

It looks like it is mostly a wrapper around lodepng but I'm not certain what the output format is so I can't reproduce it directly.

**Comment by ModeratorPS** [comment]
+1

**Comment by gpambrozio** [comment]
See [here](https://github.com/bigtreetech/PandaTouch/issues/108#issuecomment-2278942042)

**Comment by dilixi** [comment]
> Can we get the image conversion tool for Linux and macOS - would it be possible to release the source code so that we can compile it ourselves?
> 
> It looks like it is mostly a wrapper around lodepng but I'm not certain what the output format is so I can't reproduce it directly.

@andypiper 

Hi,
there is [online tool](https://pandatouch.us.kg/) to change the panda image, and you can use it on local by this [rep](https://github.com/bigtreetech-beta/PandaTouch_Addtion_IMG).

And please close this issue thanks.
