### ISSUE TITLE
Can't set bedtemp above 100°C

### ISSUE THREAD

**Issue by G4Cab** [bigtreetech/PandaTouch#77]
![20240427_172727](https://github.com/bigtreetech/PandaTouch/assets/34376785/e8655539-7fb2-4ed7-83be-6dae683fdfb0)

Living in germany with 240V / 50Hz we are able to get up to 110°C with the X1-series.
In countrys with 120V / 60Hz you're allowed to get up to 120°C with the X1-series.

I think the limit was set, with only the P1-series in mind.

So please remove this limiter ;)

**Comment by looxonline** [comment]
Thanks for reporting. We will discuss it internally and add a fix to a coming firmware release.

**Comment by BTTJUSTIN** [comment]
This feature was implemented in FW version V1.0.5
