### ISSUE TITLE
Z-axis buttons reverted

### ISSUE THREAD

**Issue by r0mar0ma** [bigtreetech/PandaTouch#80]
Buttons which are moving a plate in Z-axis are working in reverce direction.
Top buttons are moving the plate to the bottom, and bottom buttons are moving the plate to the top.
And also they have incomprehensible icons.

Firmware 1.0.3

**Comment by philchfree** [comment]
Already closed https://github.com/bigtreetech/PandaTouch/issues/7

Problem for BTT is the panda touch can be used on A1 series and not only P1

**Comment by LiamRay10** [comment]
> Already closed #7
> 
> Problem for BTT is the panda touch can be used on A1 series and not only P1

Then just make it printer to printer basis, example, "if printer=p1 or x1, then set z icons to classic, if printer=a1 or a1 mini, then set z icons to bedslinger"

**Comment by LiamRay10** [comment]
and the z still moves upward on the a1 aswell in the same way you would visialize it.

**Comment by philchfree** [comment]
> and the z still moves upward on the a1 aswell in the same way you would visialize it.

Yes but in this case it works, clicking UP moves the head up because that is the way Z is increased while on the P1/X1 to increase Z by clicking UP the bed goes down...

**Comment by philchfree** [comment]
> > Already closed #7
> > Problem for BTT is the panda touch can be used on A1 series and not only P1
> 
> Then just make it printer to printer basis, example, "if printer=p1 or x1, then set z icons to classic, if printer=a1 or a1 mini, then set z icons to bedslinger"

That's what is suggested in this same thread https://github.com/bigtreetech/PandaTouch/issues/7

**Comment by bigtreetech** [comment]
Inverting button order but not function in 1.0.5

**Comment by BTTJUSTIN** [comment]
This feature was implemented in FW version V1.0.5
