### ISSUE TITLE
Revert files order in printer tab

### ISSUE THREAD

**Issue by r0mar0ma** [bigtreetech/PandaTouch#83]
Currently files in printer tab are showing in forward order. But reverse order is much preferable, because in most cases it needs to print last printed file. Currently it requires really a lot of time to scroll down if you have tens of files on SD card.
And actually native printer interface is showing files in reverse order.

Also it will be helpful to sort them by date (in reverse order), not by the order how they are placed in FAT structure on the card. But not sure do the device have sufficient hardware resources for that...

**Comment by BTTJUSTIN** [comment]
Thanks for making this suggestion. We will discuss it internally and let you know if it will be scheduled for a future firmware release

**Comment by dilixi** [comment]
> Currently files in printer tab are showing in forward order. But reverse order is much preferable, because in most cases it needs to print last printed file. Currently it requires really a lot of time to scroll down if you have tens of files on SD card. And actually native printer interface is showing files in reverse order.
> 
> Also it will be helpful to sort them by date (in reverse order), not by the order how they are placed in FAT structure on the card. But not sure do the device have sufficient hardware resources for that...

@r0mar0ma 

Hi,
This was implemented on V1.0.5,Please close this issue,thanks.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.5
