### ISSUE TITLE
3rd party light controls

### ISSUE THREAD

**Issue by Foroxon** [bigtreetech/PandaTouch#84]
I have an additional LED strip to fix P1S's poor factory light issue.
It would be cool to have the ability to control that light from the Panda Touch screen.
I'm using [WLED](https://github.com/Aircoookie/WLED) controller for my additional light.
Could you add some configurable webhook or something like that to control it?
Thanks!

**Comment by scobby** [comment]
I use home assistant for that case, you can sync the light entitiy from the printer to every other light in your home.

**Comment by Foroxon** [comment]
> I use home assistant for that case, you can sync the light entitiy from the printer to every other light in your home.

Yes, I did the same HA automation for 3rd party light. But there is a 2-3 seconds latency between factory and 3rd party light.

**Comment by BTTJUSTIN** [comment]
Hi, the 3rd party light controls function will be enabled in our new product ,please pay attention to our new product releases
