### ISSUE TITLE
Bambu Lab account security?

### ISSUE THREAD

**Issue by worstimeline** [bigtreetech/PandaTouch#89]
I was just wondering... What measures are in place on the Panda Touch 1.0.4 firmware, to ensure that our Bambu Lab account credentials aren't going anywhere besides Bambu Lab?

**Comment by looxonline** [comment]
The panda touch only has access to the BBL servers. Anyone is welcome to wireshark it to confirm.

**Comment by looxonline** [comment]
> @looxonline sure, but, what's happening on the PT itself can't be wiresharked. Does the PT ever check in with BTT or elsewhere periodically?

Wireshark monitoring will provide you with full insight about where the PT is communicating to. It is quite simple to set up at router level so that you can monitor all comms from a particular device. As I said in my previous message, it communicates only with the BBL servers.
