### ISSUE TITLE
Add jpg to title screen

### ISSUE THREAD

**Issue by missile150** [bigtreetech/PandaTouch#93]
On the main print screen while printing can we get it to display the print jpg and not just the name of the print?  Like the display icon on the X1 series.

Thanks.

**Comment by missile150** [comment]
Already included in another request.

**Comment by missile150** [comment]
Already a topic elsewhere.

**Comment by gpambrozio** [comment]
I second that. I know it's possible since my home assistant integration does it. If you need the code that does this seems to be here: https://github.com/greghesp/ha-bambulab/blob/main/custom_components/bambu_lab/pybambu/bambu_client.py#L68

**Comment by bigtreetech** [comment]
Duplicate
