### ISSUE TITLE
panda touch beat V1.04

### ISSUE THREAD

**Issue by fred28tft** [bigtreetech/PandaTouch#94]
I wan't a firmware V1.04 please. I

**Comment by rtcmay** [comment]
same here

**Comment by poli27** [comment]
yes

**Comment by looxonline** [comment]
Very soon now. Just a final bit of polish before release.

**Comment by fred28tft** [comment]
the screen flashes when the printer starts and refuses to start when it is in DC5V, it only works in battery mode. Update V1.04 BETA 8.
